feat: initial commit
terraform-ibm-modules/terraform-ibm-powervs-powerha pull request #90
Opened 2024-03-28 15:27 UTC by maulikcapg

### Description

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-28 15:33 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                "poworha",
spelling mistake: power

2024-03-28 15:34 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                                "powervs-quickstart"
I don't think this is Quickstart

2024-03-28 15:34 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                                    "displayname": "Osaka 21 (osa21)",
osa21 is now PER

2024-03-28 15:51 UTC, surajsbharadwaj requested changes
Please use spell check for all your files.
Also you are using custom powerVS workspace. 
you should be deploying the the created workspace of landing zone..
next, where is the code for connection to transit gateway for your custom workplace to landing zone ?

2024-03-28 15:51 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                                    "displayname": "Tokyo 04 (tok04)",
tok04 as well

2024-03-28 15:51 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                                    "url": "https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-powervs-powerha/main/PowerVS-PowerHA-Diagram.svg",
once folder changes , change the reference architecture path. Should be under **reference-architecture** folder

2024-03-28 15:51 UTC, surajsbharadwaj commented on solution/standard_powervs/locals.tf
> +  pi_per_enabled_dc_list = ["dal10", "dal12", "wdc06", "wdc07", "mad02", "mad04", "eu-de-1", "eu-de-2", "sao01", "sao04"]
update the list. osa21 and tok04

2024-03-29 10:37 UTC, maulikcapg commented on ibm_catalog.json
> +                                "powervs-quickstart"
As currently we are using this as pre-requisite and tested using powervs-quickstart only.

2024-04-01 15:52 UTC, surajsbharadwaj commented on ibm_catalog.json
> +                                "powervs-quickstart"
this should be changed to PowerVS workspace flavour may be

2024-04-03 15:55 UTC, surajsbharadwaj commented
@maulikcapg Please update workspace version to 1.10.0 . syd05 is now PER enabled

2024-04-05 07:44 UTC, surajsbharadwaj commented
@maulikcapg  Please update workspace version to 1.11.0 . lon06 is now PER enabled

2024-04-12 11:34 UTC, Jeskiran commented on modules/cloud-connection-network-attach/versions.tf
Better to align with specific version of terrform to avoid regression issues

2024-04-12 11:55 UTC, Jeskiran commented on modules/powervs-instance-ansible-config/template-files/ansible_config.py.tftpl
> +VG_DEFAULT = {"name": "","rg_name":"","physical_volume_count":1, "type": 'original'}
As discussed, VG need to be scalable

2024-04-12 11:55 UTC, Jeskiran commented on modules/powervs-instance-custom/locals.tf
> +  shared_volume_storage_type = "tier3"
we need to take tier info from user as optional input

2024-04-19 08:45 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/outputs.tf
> +  description = "installl packages script path"
spell check install

2024-04-19 08:46 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "Virtual privide cloud's VSI ip address to access private powervs nodes"
spell check. Use VS code and do spell check everywhere

2024-04-19 08:47 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "aix image"
AIX image id

2024-04-19 08:47 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "Name of file system"
Provide better description

2024-04-19 08:48 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "details of reserved ip"
Case

2024-04-19 08:55 UTC, surajsbharadwaj requested changes
Please perform spell checks, sentence case with upper case for beginning words,
Also write a basic example which runs your complete solution which doesn't require pre-req id, which can test your modules. This Is required for the pipeline to run and validate your code..
We can connect over Webex for the last point.

2024-04-19 08:55 UTC, surajsbharadwaj commented on modules/powervs-instance-ansible-config/variables.tf
> +variable "powerha_resource_group_list" {
Case

2024-04-19 08:55 UTC, surajsbharadwaj commented on modules/powervs-instance-custom/variables.tf
> +  description = "count of dedicated voulumes need to be attach to each powervs instance."
Case

2024-04-19 08:55 UTC, surajsbharadwaj commented on modules/powervs-instance-custom/variables.tf
Use sentence Case. Starting with Uppercase

2024-04-19 08:55 UTC, surajsbharadwaj commented on modules/powervs-workspace-update/outputs.tf
Same as other files. Sentence case

2024-04-19 08:55 UTC, surajsbharadwaj commented on modules/powervs-workspace-update/variables.tf
Sentence case for description

2024-04-19 08:55 UTC, surajsbharadwaj commented on solution/standard_powervs/versions.tf
> +      version = "=1.61.0"
use 1.64.1

2024-04-19 09:22 UTC, maulikcapg commented on modules/powervs-instance-custom/locals.tf
> +  shared_volume_storage_type = "tier3"
done

2024-04-19 09:22 UTC, maulikcapg commented on modules/powervs-instance-ansible-config/template-files/ansible_config.py.tftpl
> +VG_DEFAULT = {"name": "","rg_name":"","physical_volume_count":1, "type": 'original'}
done

2024-04-22 12:06 UTC, surajsbharadwaj commented on modules/powervs-instance-custom/variables.tf
> +  description = "A unique identifier for resources. The identifier must begin with a lowercase letter and end with a lowercase letter or a number. This prefix will be prepended to any resources provi
missing validation check here. Description says max 8 characters. But no validation found

2024-04-22 12:08 UTC, surajsbharadwaj commented on solution/standard_powervs/versions.tf
> +      version = ">=1.64.1"
the solution has to be locked to a specific version . Only for solutions . Not for submodules.
Use '='

2024-04-22 12:09 UTC, surajsbharadwaj requested changes
please see additional comments

2024-04-23 07:02 UTC, maulikcapg commented on modules/powervs-instance-ansible-config/outputs.tf
> +  description = "installl packages script path"
done

2024-04-23 07:02 UTC, maulikcapg commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "Virtual privide cloud's VSI ip address to access private powervs nodes"
done

2024-04-23 07:02 UTC, maulikcapg commented on modules/powervs-instance-ansible-config/variables.tf
> +  description = "aix image"
done

2024-04-29 06:07 UTC, maulikcapg commented on solution/standard_powervs/versions.tf
> +      version = ">=1.64.1"
done

2024-04-29 06:07 UTC, maulikcapg commented on modules/powervs-instance-custom/variables.tf
> +  description = "A unique identifier for resources. The identifier must begin with a lowercase letter and end with a lowercase letter or a number. This prefix will be prepended to any resources provi
yes added required validations in module also

2024-04-29 09:26 UTC, surajsbharadwaj approved these changes

2024-04-29 09:33 UTC, maulikcapg commented
/run pipeline

2024-04-29 10:51 UTC, surajsbharadwaj commented
@maulikcapg you need to write an example with default values to so that pipeline runs your example

2024-05-03 06:21 UTC, surajsbharadwaj commented
/run pipeline

2024-05-03 06:42 UTC, surajsbharadwaj commented
/run pipeline

2024-05-03 06:50 UTC, surajsbharadwaj commented
/run pipeline

2024-05-06 09:18 UTC, surajsbharadwaj commented
/run pipeline

2024-05-06 14:32 UTC, maulikcapg commented
/run pipeline

2024-05-06 14:58 UTC, surajsbharadwaj commented
/run pipeline

2024-05-06 15:08 UTC, surajsbharadwaj commented
/run pipeline

2024-05-06 19:04 UTC, surajsbharadwaj approved these changes

2024-05-06 19:05 UTC, merged

2024-05-06 19:07 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-powerha/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: